name: Release Package

on:

  push:
    tags:
      - 'v*'  # Only run on version tags like v0.3.1

jobs:
  release:
    name: Publish Python Package
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Pypi dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install .[pypi]
          

      - name: Extract version
        id: get_version
        shell: bash
        run: |
          VERSION=$(python scripts/get_version.py)
          echo "Version from pyproject.toml: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
 
      - name: Build package
        uses: ./.github/actions/build-package

      - name: Check tag version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          if [ "$TAG_VERSION" != "${{ steps.get_version.outputs.version }}" ]; then
            echo "Git tag version (v$TAG_VERSION) does not match pyproject.toml version (${{ steps.get_version.outputs.version }})"
            exit 1
          fi

      - name: Set repository URL
        id: repo-url
        run: |
            PYPI_URL='https://upload.pypi.org/legacy/'
            echo "Pypi URL: $PYPI_URL"
            echo "url=$PYPI_URL" >> $GITHUB_OUTPUT

      - name: Publish to PyPI / TestPyPI
        uses: ./.github/actions/publish-to-pypi
        with:
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: ${{ steps.repo-url.outputs.url }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ./.github/actions/create-github-release
        with:
            tag_name: ${{ github.ref_name }}
            release_title: "Release ${{ github.ref_name }}"
            release_body: "Automatic release of version ${{ github.ref_name }}"
