
---
name: Update Documentation

on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'ocean4dvarnet/**'

jobs:

  update-mkdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doc dependecies 
        run: |
          pip install --upgrade pip
          pip install tomlq
          PIP_DOC_PACKAGE=$(tomlq -r '.project."optional-dependencies".doc | join(" ")' pyproject.toml)
          echo "Installing doc dependencies : $PIP_DOC_PACKAGE"
          pip install $PIP_DOC_PACKAGE

      - name: Deploy MkDocs to GitHub Pages
        run: |
          mkdocs gh-deploy --force
